### ISSUE TITLE
Configurable Peer Endpoint Value

### ISSUE THREAD

**Issue by reafian** [donaldzou/wireguard-dashboard#60]
**Is your feature request related to a problem? Please describe.**
My Wireguard server is on a 192.168 address behind a router. The port 51820 has been forwarded to my Wireguard server and I access it using a dynamic host name. This all works perfectly well.

Generating a QR code for a new connection sets a peer endpoint of the local IP address of the Wireguard server and not the hostname that I use. I'd like that to change.

**Describe the solution you'd like**
Under the Configurations / wg0 page have a global value that can be set as the peer endpoint. I suspect it would be a value that would apply to all connections under a connection rather than something that would be set on a per-client basis.

**Comment by bluecraank** [comment]
Agree!

**Comment by nicedevil007** [comment]
@ricohard 

I have my site sitting on a dyndns as well so I may ask you how you where able to save a dyndns address to the config in the dashboard? I always get an error to put in a static IP adress format.

With wireguard itself it is possible to a dyndnsadress.

**Comment by donaldzou** [comment]
@ricohard I see, because I used a library to search for the default interface's IP address. I will add a another setting in the setting page in the next release ;)

**Comment by ricohard** [comment]
@nicedevil007 I can't, that's why I asked for it to be possible. :-)

With the dashboard it's not possible to manually set the server endpoint which I think is needed. I suppose it's debatable whether the way the current endpoint IP is generated is a bug or not because, I think, there's an assumption there that the server has a single internet addressable interface (I wonder what would happen if the machine had multiple interfaces... :-/ ) and for a machine that only has internal addresses there's no way that's a reachable address.

I suppose it really should do a lookup on the address and determine if it's a public address or not and if it's not then it should probably get the public address somehow but I'm really not trying to create more work for poor @donaldzou.

Just a box so the endpoint can be set manually would be enough for me.

**Comment by nicedevil007** [comment]
Ahh ok, ty for clearing things up! This is my first day getting WireGuard up and running with a dashboard in a lxc container! So didn't understand everything at first time but it is getting clearer now 😎

**Comment by willudovich** [comment]
I'll add a vote for this as well! Not a major issue to edit the config on the peer once I've imported the config, but adding the peer endpoint as a configurable value so I can just set a DNS name would be perfect.

**Comment by donaldzou** [comment]
Thank you guys for voting this, I'll be adding this to the next release :) Stay tuned!! But university is coming up so I might push the next release in early september. Sorry :(
